services:
  api:
    image: kapoko/strapi:latest
    env_file: .env
    ports:
      - 1337:1337
    volumes:
      - ./api/strapi:/usr/src/api/strapi
    depends_on:
      - db

  db:
    image: mongo:8
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
      - ./db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
