version: '3'

services:
  api:
    image: kapoko/kasperkoman:api
    volumes:
      - .env:/usr/src/api/.env
      - ./volumes/uploads:/usr/src/api/strapi/public/uploads
    ports:
      - 1337:1337
    env_file: .env
    depends_on:
      - db
    restart: always

  app:
    image: kapoko/kasperkoman:app
    ports:
      - 5000:5000
    env_file: .env
    volumes: 
      - ./volumes/logs:/opt/app/logs
    restart: always

  db: 
    image: kapoko/kasperkoman:db
    ports:
      - 27017:27017
    env_file: .env
    volumes: 
      - ./volumes/db:/data/db
    restart: always