services:
  api:
    build: api
    env_file: .env
    ports:
      - 1337:1337
    volumes:
      - ./api/strapi:/usr/src/api/strapi
    depends_on:
      - db

  db-old:
    image: mongo:8
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
      - ./db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh

  db:
    image: postgres:latest
    ports: 
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
